name: Upload Excess to IC Source

on:
  schedule:
    - cron: "0 */6 * * *"        # every 6 hours
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (generate CSV only, no FTP)"
        type: boolean
        default: false

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      # Supabase + FTP secrets mapped to envs the script reads
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      ICSOURCE_FTP_USER: ${{ secrets.ICSOURCE_FTP_USER }}
      ICSOURCE_FTP_PASS: ${{ secrets.ICSOURCE_FTP_PASS }}
      DRY_RUN: ${{ inputs.dry_run }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---- here's the important change ----
      - name: Install deps (lockfile if present)
        run: |
          set -euxo pipefail
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "Lockfile found -> npm ci"
            npm ci
          else
            echo "No lockfile -> npm install"
            npm install --no-audit --no-fund
          fi
      # --------------------------------------

      - name: Export & (optionally) Upload
        run: |
          mkdir -p out
          node scripts/export-and-upload-icsource.mjs

      - name: Upload CSV as artifact (so you can download it)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verified_inventory
          path: out/verified_inventory.csv
          if-no-files-found: warn






